#!/usr/bin/env python

from src.Console import Console
import sys
import requests
from requests.exceptions import HTTPError

console = Console()
console.run()

try:
    response = requests.get('https://api.github.com/user/repos', headers={'Authorization': 'token ' + console.args.token})
    print(response.json())
except HTTPError as http_error:
    print(f'HTTP error occurred: {http_error}', file=sys.stderr)
except Exception as err:
    print(f'Other error occurred: {err}', file=sys.stderr)
